# Generated by Django 6.0.2 on 2026-03-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_trainer_trainer_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
    ]
