# Generated by Django 6.0.2 on 2026-03-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_rename_course_image_course_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='trainer_photo',
            new_name='photo',
        ),
    ]
