# Generated by Django 6.0.2 on 2026-03-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_rename_trainer_photo_trainer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
